services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_dev_template
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.docker
    stdin_open: true
    tty: true